name: Auto Sitemap Generator
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # روزانه در نیمه‌شب UTC اجرا می‌شود

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # تمام تاریخچه commitها را دریافت می‌کند

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://pingsnet.github.io"
          change-frequency: "weekly"
          include-extension: ".html"
          exclude-extension: ".md"
          trailing-slash: false
          priority: "0.8"

      - name: Commit and Push Changes
        run: |
          # تنظیمات Git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # اضافه کردن و commit تغییرات
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generated sitemap [skip ci]"
          
          # Push تغییرات با استفاده از توکن خودکار
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
